# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: flapper-news-development
  username: chryus
  password:
  host: localhost

test: &test
  <<: *default
  database: flapper-news-test
  username: chryus
  password:
  host: localhost

cucumber:
  <<: *test

production:
  <<: *default
  database: flapper-news-production
